version: 2

sources:
  - name: source_platform_commons 
    schema: pc_staging
    tables:
      - name: user_data_int
        identifier: User_DATA_v2
        description: Platform common api
      - name: applicant_data_2023_int
        identifier: Applicant_Data_2023
        description: Platform common api
      - name: applicant_data_2024_int
        identifier: Applicant_Data_2024
        description: Platform common api
      - name: applicant_data_2025_int
        identifier: Applicant_Data_2025
        description: Platform common api
      - name: child_attendance_int
        identifier: Child_Attendence
        description: Platform common api
      - name: class_ops_master_data_int
        identifier: Class_ops_master_data
        description: Platform common api
      - name: credit_data_int
        identifier: Credit_Data
        description: Platform common api
      - name: events_data_int
        identifier: Events_Data
        description: Platform common api
      - name: fellow_applicant_data_int
        identifier: Fellow_Applicant_Data
        description: Platform common api
      - name: fundraising_donations_int
        identifier: Fundraising_Donations
        description: Platform common api
      - name: students_data_int
        identifier: Students_Data
        description: Platform common api
      - name: school_id_int
        identifier: School_IDs
        description: Platform common api
      - name: target_settings_int
        identifier: Target_Setting_
        description: Platform common api
      - name: volunteer_retention_d_int
        identifier: Volunteer_Retention_Data
        description: Platform common api

  - name: crm_data
    schema: crm_staging
    tables:
      - name: pocs
        identifier: pocs
        description: CRM points of contact data
      - name: mous
        identifier: mous
        description: CRM Memorandum of Understanding data
      - name: cities
        identifier: cities
        description: CRM cities master data
      - name: states
        identifier: states
        description: CRM states master data
      - name: partner_agreements
        identifier: partner_agreements
        description: CRM partner agreements and contracts
      - name: poc_partners
        identifier: poc_partners
        description: CRM point of contact and partner relationships
      - name: manager_co
        identifier: manager_co
        description: CRM manager and company relationships
      - name: partners
        identifier: partners
        description: CRM partners master data
      - name: partner_cos
        identifier: partner_cos
        description: CRM partner company relationships
      - name: meetings
        identifier: meetings
        description: CRM meetings and interactions data

    
