version: 2

sources:
  - name: source_platform_commons 
    schema: staging
    tables:
      - name: user_data_int
        identifier: User_DATA_v2
        description: Platform common api
      - name: applicant_data_2023_int
        identifier: Applicant_Data_2023
        description: Platform common api
      - name: applicant_data_2024_int
        identifier: Applicant_Data_2024
        description: Platform common api
      - name: child_attendance_int
        identifier: Child_Attendence
        description: Platform common api
      - name: class_ops_master_data_int
        identifier: Class_ops_master_data
        description: Platform common api
      - name: credit_data_int
        identifier: Credit_Data
        description: Platform common api
      - name: events_data_int
        identifier: Events_Data
        description: Platform common api
      - name: fellow_applicant_data_int
        identifier: Fellow_Applicant_Data
        description: Platform common api
      - name: fundraising_donations_int
        identifier: Fundraising_Donations
        description: Platform common api
      - name: mad_opportunity_int
        identifier: MAD_Opportunity_2909
        description: Platform common api
      - name: students_data_int
        identifier: Students_Data
        description: Platform common api
      - name: school_id_int
        identifier: School_IDs
        description: Platform common api
      - name: target_setting_int
        identifier: Target_Setting_
        description: Platform common api
      - name: volunteer_retention_d_int
        identifier: Volunteer_Retention_Data
        description: Platform common api

    
